require("danny")

print("Orale wuey") 
print(" ")
print("--in nvim")
print(":so -to source file ")
print("<leader> pv - Enter file manager")
print(" ")
print("--netrw ")
print("% -Create file")
print("d -create directory ")
print(" ")
print("--harpoon")
print("<leader>a -add file to menu")
print("<C-e> -toggle_quick_menu")
print("<C-h> -nav_file 1")
print("<C-t> -nav_file 2")
print("<C-n> -nav_file 3")
print("<C-s> -nav_file 4")
print(" ")
print("--telescope")
print("<leader>pf -project find")
print("<leader>ps") 
print(" ")
print("--undotree")
print("<leader>u -menu")
print(" ")
print("--packer")
print(":PackerSync -syncs plugins ")
